services:
  grafana:
    image: grafana/grafana:latest
    container_name: arz-grafana
    ports:
      - '3000:3000'
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=arz-o11y-assistant-app
      - GF_FEATURE_TOGGLES_ENABLE=extensionSidebar
      - GF_LOG_LEVEL=debug
      - LIBRECHAT_URL=${LIBRECHAT_URL:-http://localhost:3080}
    volumes:
      - ./dist:/var/lib/grafana/plugins/arz-o11y-assistant-app
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
